version: "3"

services:
  server:
    build: .
    image: hapijs.com
    command: bash -c "npm i && npm run dev"
    volumes:
      - ".:/usr/server"
    ports:
      - "3000:3000"
    depends_on:
      - redis
  
  redis:
    image: redis:alpine

